In [1]:
from sklearn.metrics import brier_score_loss
import numpy as np

# True values
y_true = np.array([0.1, 0.5, 0.8])
# Predicted probabilities
y_prob = np.array([0.2, 0.6, 0.7])

# Calculate Brier score
brier_score = brier_score_loss(y_true, y_prob)
print("Brier Score for numerical targets:", brier_score)

ValueError: Only binary classification is supported. The type of the target is continuous.

In [2]:
# True labels (binary)
y_true_cat = np.array([0, 1, 1])
# Predicted probabilities for positive class
y_prob_cat = np.array([0.2, 0.8, 0.9])

# Binarize true labels if needed
from sklearn.preprocessing import label_binarize
y_true_bin = label_binarize(y_true_cat, classes=[0, 1])

# Calculate Brier score
brier_score_cat = brier_score_loss(y_true_bin, y_prob_cat)
print("Brier Score for categorical targets:", brier_score_cat)

Brier Score for categorical targets: 0.029999999999999995


In [3]:
from sklearn.metrics import brier_score_loss
import numpy as np

# True labels (multiclass)
y_true_multiclass = np.array([0, 1, 2, 1, 0])
# Predicted probabilities for each class
y_prob_multiclass = np.array([[0.7, 0.2, 0.1],
                              [0.3, 0.5, 0.2],
                              [0.1, 0.3, 0.6],
                              [0.4, 0.4, 0.2],
                              [0.6, 0.3, 0.1]])

# Calculate Brier score for each class
brier_scores = []
for class_idx in range(y_prob_multiclass.shape[1]):
    y_true_class = (y_true_multiclass == class_idx).astype(int)
    y_prob_class = y_prob_multiclass[:, class_idx]
    brier_scores.append(brier_score_loss(y_true_class, y_prob_class))

# Average Brier score across all classes
average_brier_score = np.mean(brier_scores)
print("Average Brier Score for multiclass targets:", average_brier_score)

Average Brier Score for multiclass targets: 0.10666666666666667


In [4]:
from sklearn.linear_model import LogisticRegression
import numpy as np

# Generate some sample data
X = np.random.rand(100, 2)
y = np.random.randint(0, 2, size=100)  # Binary classification

# Train a logistic regression model
model = LogisticRegression()
model.fit(X, y)

# Obtain predicted probabilities
y_pred_proba = model.predict_proba(X)

print("Predicted probabilities for the first 5 samples:")
print(y_pred_proba[:5])

Predicted probabilities for the first 5 samples:
[[0.48544099 0.51455901]
 [0.48164317 0.51835683]
 [0.4304759  0.5695241 ]
 [0.46084434 0.53915566]
 [0.5361034  0.4638966 ]]


In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Sample data with string labels
X = np.random.rand(100, 2)
y_str = np.random.choice(['class_a', 'class_b', 'class_c'], size=100)

# Encode string labels to numerical values
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y_str)

# Train a logistic regression model
model = LogisticRegression()
model.fit(X, y)

# Obtain predicted probabilities
y_pred_proba = model.predict_proba(X)

print("Predicted probabilities for the first 5 samples:")
print(y_pred_proba[:5])

Predicted probabilities for the first 5 samples:
[[0.27163879 0.35803453 0.37032668]
 [0.22005674 0.41612156 0.36382169]
 [0.29731111 0.36397261 0.33871628]
 [0.28983247 0.36147961 0.34868792]
 [0.23285168 0.41956286 0.34758547]]
